@startuml
class RenameCommand {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> Aliases : string[] <<get>>
    + <<override>> Execute(args:string, state:GameState) : void
}
BaseCommand <|-- RenameCommand
@enduml
