@startuml
class CommandHandler {
    - <<readonly>> _commands : Dictionary<string, ICommand>
    - _inputHandler : Action<string>
    - _currentState : GameState?
    + InputHandler : Action<string> <<get>> <<set>>
    + CommandHandler()
    - DefaultInputHandler(input:string) : void
    + RegisterCommand(command:ICommand) : void
    + ProcessInput(input:string) : void
    + ExecuteCommand(input:string, state:GameState) : bool
    + GetCommands() : IEnumerable<ICommand>
}
@enduml
