image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  GIT_DEPTH: "1"
  DOTNET_CLI_HOME: "/tmp"

pages:
  stage: deploy
  tags:
    - dotnet
  script:
    - dotnet tool install -g docfx
    - docfx ./docs/docfx.json
    - rm -rf public/*
    - mv ./docs/_site/* public/
  artifacts:
    paths:
      - public
  only:
    - main