image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  GIT_DEPTH: "1"
  DOTNET_CLI_HOME: "/tmp"  # Prevents some issues with permissions in CI
  PATH: "$PATH:/root/.dotnet/tools"  # Add dotnet global tools to PATH

pages:
  stage: deploy
  tags:
    - dotnet
  script:
    # Install docfx if not already installed
    - dotnet tool install -g docfx
    # Verify that docfx is installed and available
    - docfx --version
    # Run docfx build (no need for pwsh)
    - docfx ./docs/docfx.json
    # Clean the public directory to avoid "not empty" errors
    - rm -rf public/*
    # Ensure the build output is placed in the 'public' directory
    - mv ./docs/_site/* public/
  artifacts:
    paths:
      - public
  only:
    - main  # Deploy only when changes are pushed to the main branch
