# The Docker image that will be used to build your app
image: mcr.microsoft.com/dotnet/sdk:9.0
# Functions that should be executed before the build script is run
before_script:
  - dotnet tool install -g docfx
pages:
  script:
    - ~/.dotnet/tools/docfx ./docs/docfx.json
    - rm -rf public/*
    - mv ./docs/_site/* public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
