image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  GIT_DEPTH: "1"

pages:
  stage: deploy
  tags:
    - dotnet
  script:
    - dotnet tool install -g docfx
    - pwsh ./build_docs.ps1 -Environment gitlab
  artifacts:
    paths:
      - public
  only:
    - main
