extensions:
  - .cs
  - .csproj

ignored_dirs:
  - bin
  - obj
  - output
  - Scripts
  - .git
  - .vscode
  - _site
  - api
  - build_logs
  - docs

ignored_files: []
source_dirs:
  - "."
  - "../RPG.WorldBuilder"
output_dir: "output"
max_workers: 32
text_output: "."
mirror_dir_structure: false