@startuml
abstract class BaseCommand {
    + {abstract} Name : string <<get>>
    + {abstract} Description : string <<get>>
    + <<virtual>> Aliases : string[] <<get>>
    + {abstract} Execute(args:string, state:GameState) : void
}
ICommand <|-- BaseCommand
@enduml
