@startuml
class Magician {
    + MagicPower : int <<get>> <<set>>
    + KnownSpells : List<Spell> <<get>> <<set>>
    + <<virtual>> CastSpell(spell:Spell, target:Person) : void
}
Person <|-- Magician
@enduml
