@startuml
class Sorcerer {
    - gameState : GameState?
    +  <<event>> OnTransformToSith : Action? 
    - evilLevel : int
    + EvilLevel : int <<get>> <<set>>
    + Initialise(state:GameState) : void
    - TransformToSith() : void
}
Magician <|-- Sorcerer
@enduml
