@startuml
class Sorcerer {
    - gameState : GameState?
    +  <<event>> OnTransformToSith : Action? 
    - evilLevel : int
    + EvilLevel : int <<get>> <<set>>
    + Initialize(state:GameState) : void
    - TransformToSith() : void
    # <<override>> FormatSpeech(message:string) : string
}
Magician <|-- Sorcerer
@enduml
