@startuml
class WorldRegion {
    + NameId : int <<get>> <<set>>
    + DescriptionId : int <<get>> <<set>>
}
class WorldData {
}




WorldRegion o-> "Position" Vector2


WorldData o-> "Header" Header
WorldData o-> "Resources" ResourceTable



@enduml
