@startuml
class HelpCommand {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> Execute(args:string, state:GameState) : void
}
BaseCommand <|-- HelpCommand
HelpCommand o-> "_commandHandler" CommandHandler
@enduml
